# Generated by Django 5.0.4 on 2024-09-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('ratings', models.FloatField()),
                ('category', models.CharField(choices=[('BC', 'buttercake'), ('BM', 'buttermilk'), ('CS', 'chesseslice'), ('CO', 'cococola'), ('CG', 'cowgheee'), ('CU', 'curd'), ('IC', 'icecreams'), ('KU', 'kulfi'), ('LA', 'lays'), ('MA', 'maggi'), ('MS', 'milkshake'), ('SB', 'sweetbox')], max_length=2)),
                ('product_image', models.ImageField(upload_to='items')),
            ],
        ),
    ]
